version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://cpmuser:cpmpassword@db:5432/cpmdb
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cpmuser
      - POSTGRES_PASSWORD=cpmpassword
      - POSTGRES_DB=cpmdb
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
